<?php $this->setPriceDataObject($this->getSource()) ?>

<?php if ((float) $this->getSource()->getFeeAmount()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('auction')->__('Fee Auction tem-sa-or-to') ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseFeeAmount(), $this->getSource()->getFeeAmount()); ?>
        </td>
    </tr>
<?php endif; ?>